/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.lexer;

import java.io.*;
import calculadora.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TClasse(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFilhaDaClasse(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComeca(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTermina(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TObjeto(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVariavel(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConstante(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInteiro(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBool(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReal(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIniciaProcdm(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProcedimento(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParEsquerdo(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParDireito(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFuncao(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSe(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSenao(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEntao(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnquanto(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVerdadeiro(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalso(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TE(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOu(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEComercial(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontoVirgula(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVirgula(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicializacao(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAtribuicao(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenos(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMais(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMult(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMod(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComp(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenor(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNegacao(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPonto(line, pos); }
    Token new37(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumInteiro(text, line, pos); }
    Token new38(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumReal(text, line, pos); }
    Token new39(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentificador(text, line, pos); }
    Token new40(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TClIdentificador(text, line, pos); }
    Token new41(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComent(text, line, pos); }
    Token new42(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVazio(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {37, 37, 6}, {38, 38, 7}, {40, 40, 8}, {41, 41, 9}, {42, 42, 10}, {43, 43, 11}, {44, 44, 12}, {45, 45, 13}, {46, 46, 14}, {47, 47, 15}, {48, 48, 16}, {49, 57, 17}, {58, 58, 18}, {59, 59, 19}, {60, 60, 20}, {61, 61, 21}, {65, 90, 22}, {95, 95, 23}, {97, 97, 24}, {98, 98, 25}, {99, 99, 26}, {100, 100, 24}, {101, 101, 27}, {102, 102, 28}, {103, 104, 24}, {105, 105, 29}, {106, 110, 24}, {111, 111, 30}, {112, 112, 31}, {113, 113, 24}, {114, 114, 32}, {115, 115, 33}, {116, 116, 34}, {117, 117, 24}, {118, 118, 35}, {119, 122, 24}, {123, 123, 36}, {192, 192, 37}, {193, 193, 38}, {194, 194, 39}, {195, 195, 40}, {199, 199, 41}, {201, 201, 42}, {202, 202, 43}, {205, 205, 44}, {211, 211, 45}, {212, 212, 46}, {213, 213, 47}, {218, 218, 48}, {224, 224, 49}, {225, 225, 50}, {226, 226, 51}, {227, 227, 52}, {231, 231, 53}, {233, 233, 54}, {234, 234, 55}, {237, 237, 56}, {243, 243, 57}, {244, 244, 58}, {245, 245, 59}, {250, 250, 60}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {{46, 46, 61}, {48, 57, 62}, {98, 98, 63}, },
            {{46, 46, 61}, {48, 48, 64}, {49, 57, 65}, {69, 69, 66}, {101, 101, 67}, },
            {{61, 61, 68}, },
            {},
            {},
            {{61, 61, 69}, {62, 62, 70}, },
            {{65, 90, 71}, {95, 95, 72}, {97, 122, 73}, {192, 192, 74}, {193, 193, 75}, {194, 194, 76}, {195, 195, 77}, {199, 199, 78}, {201, 201, 79}, {202, 202, 80}, {205, 205, 81}, {211, 211, 82}, {212, 212, 83}, {213, 213, 84}, {218, 218, 85}, {224, 224, 86}, {225, 225, 87}, {226, 226, 88}, {227, 227, 89}, {231, 231, 90}, {233, 233, 91}, {234, 234, 92}, {237, 237, 93}, {243, 243, 94}, {244, 244, 95}, {245, 245, 96}, {250, 250, 97}, },
            {{65, 90, 98}, {95, 95, 99}, {97, 122, 100}, {192, 192, 101}, {193, 193, 102}, {194, 194, 103}, {195, 195, 104}, {199, 199, 105}, {201, 201, 106}, {202, 202, 107}, {205, 205, 108}, {211, 211, 109}, {212, 212, 110}, {213, 213, 111}, {218, 218, 112}, {224, 224, 113}, {225, 225, 114}, {226, 226, 115}, {227, 227, 116}, {231, 231, 117}, {233, 233, 118}, {234, 234, 119}, {237, 237, 120}, {243, 243, 121}, {244, 244, 122}, {245, 245, 123}, {250, 250, 124}, },
            {{65, 250, -24}, },
            {{65, 95, -24}, {97, 110, 73}, {111, 111, 125}, {112, 122, 73}, {192, 250, -24}, },
            {{65, 95, -24}, {97, 107, 73}, {108, 108, 126}, {109, 110, 73}, {111, 111, 127}, {112, 250, -27}, },
            {{65, 95, -24}, {97, 109, 73}, {110, 110, 128}, {111, 122, 73}, {192, 250, -24}, },
            {{65, 95, -24}, {97, 97, 129}, {98, 104, 73}, {105, 105, 130}, {106, 116, 73}, {117, 117, 131}, {118, 122, 73}, {192, 250, -24}, },
            {{65, 109, -29}, {110, 110, 132}, {111, 250, -29}, },
            {{65, 95, -24}, {97, 97, 73}, {98, 98, 133}, {99, 116, 73}, {117, 117, 134}, {118, 250, -30}, },
            {{65, 95, -24}, {97, 113, 73}, {114, 114, 135}, {115, 122, 73}, {192, 250, -24}, },
            {{65, 95, -24}, {97, 100, 73}, {101, 101, 136}, {102, 122, 73}, {192, 250, -24}, },
            {{65, 100, -34}, {101, 101, 137}, {102, 250, -34}, },
            {{65, 100, -34}, {101, 101, 138}, {102, 113, 73}, {114, 114, 139}, {115, 250, -33}, },
            {{65, 95, -24}, {97, 97, 140}, {98, 122, 73}, {192, 250, -24}, },
            {{0, 122, 141}, {124, 124, 142}, {125, 125, 143}, {126, 255, 144}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{48, 57, 145}, },
            {{46, 57, -18}, },
            {{48, 48, 146}, {49, 49, 147}, },
            {{46, 46, 61}, {48, 57, 64}, {94, 94, 148}, },
            {{46, 69, -19}, {94, 94, 148}, {101, 101, 67}, },
            {{45, 45, 149}, {48, 57, 150}, },
            {{45, 57, -68}, },
            {},
            {},
            {},
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 250, -25}, },
            {{65, 110, -27}, {111, 111, 151}, {112, 250, -27}, },
            {{65, 95, -24}, {97, 97, 152}, {98, 250, -37}, },
            {{65, 95, -24}, {97, 108, 73}, {109, 109, 153}, {110, 110, 154}, {111, 250, -29}, },
            {{65, 95, -24}, {97, 112, 73}, {113, 113, 155}, {114, 115, 73}, {116, 116, 156}, {117, 122, 73}, {192, 250, -24}, },
            {{65, 107, -28}, {108, 108, 157}, {109, 122, 73}, {192, 250, -24}, },
            {{65, 107, -28}, {108, 108, 158}, {109, 250, -131}, },
            {{65, 109, -29}, {110, 110, 159}, {111, 250, -29}, },
            {{65, 95, -24}, {97, 115, 73}, {116, 116, 160}, {117, 250, -130}, },
            {{65, 95, -24}, {97, 105, 73}, {106, 106, 161}, {107, 122, 73}, {192, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 110, -27}, {111, 111, 162}, {112, 250, -27}, },
            {{65, 95, -24}, {97, 97, 163}, {98, 250, -37}, },
            {{65, 109, -29}, {110, 110, 164}, {111, 250, -29}, },
            {{65, 113, -33}, {114, 114, 165}, {115, 250, -33}, },
            {{65, 95, -24}, {97, 116, 73}, {117, 117, 166}, {118, 250, -30}, },
            {{65, 113, -33}, {114, 114, 167}, {115, 250, -33}, },
            {{0, 255, -38}, },
            {{0, 255, -38}, },
            {},
            {{0, 255, -38}, },
            {{48, 57, 145}, },
            {{48, 49, -65}, },
            {{48, 49, -65}, },
            {{45, 45, 168}, {48, 57, 169}, },
            {{48, 57, 150}, },
            {{48, 57, 150}, },
            {{65, 107, -28}, {108, 108, 170}, {109, 250, -131}, },
            {{65, 95, -24}, {97, 114, 73}, {115, 115, 171}, {116, 122, 73}, {192, 250, -24}, },
            {{65, 100, -34}, {101, 101, 172}, {102, 250, -34}, },
            {{65, 114, -154}, {115, 115, 173}, {116, 250, -154}, },
            {{65, 116, -141}, {117, 117, 174}, {118, 250, -30}, },
            {{65, 226, -24}, {227, 227, 175}, {231, 250, -24}, },
            {{65, 114, -154}, {115, 115, 176}, {116, 250, -154}, },
            {{65, 95, -24}, {97, 103, 73}, {104, 104, 177}, {105, 122, 73}, {192, 250, -24}, },
            {{65, 227, -24}, {231, 231, 178}, {233, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 100, -34}, {101, 101, 179}, {102, 250, -34}, },
            {{65, 95, -24}, {97, 98, 73}, {99, 99, 180}, {100, 122, 73}, {192, 250, -24}, },
            {{65, 107, -28}, {108, 108, 181}, {109, 250, -131}, },
            {{65, 226, -24}, {227, 227, 182}, {231, 250, -24}, },
            {{65, 108, -129}, {109, 109, 183}, {110, 122, 73}, {192, 250, -24}, },
            {{65, 100, -34}, {101, 101, 184}, {102, 250, -34}, },
            {{65, 250, -24}, },
            {{48, 57, 169}, },
            {{48, 57, 169}, },
            {{65, 250, -24}, },
            {{65, 114, -154}, {115, 115, 185}, {116, 250, -154}, },
            {{65, 227, -24}, {231, 231, 186}, {233, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 95, -24}, {97, 97, 187}, {98, 250, -37}, },
            {{65, 110, -27}, {111, 111, 188}, {112, 250, -27}, },
            {{65, 100, -34}, {101, 101, 189}, {102, 250, -34}, },
            {{65, 95, -24}, {97, 97, 190}, {98, 250, -37}, },
            {{65, 226, -24}, {227, 227, 191}, {231, 250, -24}, },
            {{65, 115, -134}, {116, 116, 192}, {117, 250, -130}, },
            {{65, 100, -34}, {101, 101, 193}, {102, 250, -34}, },
            {{65, 250, -24}, },
            {{65, 110, -27}, {111, 111, 194}, {112, 250, -27}, },
            {{65, 95, -24}, {97, 104, 73}, {105, 105, 195}, {106, 122, 73}, {192, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 100, -34}, {101, 101, 196}, {102, 250, -34}, },
            {{65, 95, -24}, {97, 97, 197}, {98, 250, -37}, },
            {{65, 109, -29}, {110, 110, 198}, {111, 250, -29}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{32, 32, 199}, {65, 250, -24}, },
            {{65, 110, -27}, {111, 111, 200}, {112, 250, -27}, },
            {{65, 110, -27}, {111, 111, 201}, {112, 250, -27}, },
            {{65, 95, -24}, {97, 99, 73}, {100, 100, 202}, {101, 122, 73}, {192, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 109, -29}, {110, 110, 203}, {111, 250, -29}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 115, -134}, {116, 116, 204}, {117, 250, -130}, },
            {{100, 100, 205}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{65, 104, -185}, {105, 105, 206}, {106, 250, -185}, },
            {{65, 95, -24}, {97, 97, 207}, {98, 250, -37}, },
            {{65, 110, -27}, {111, 111, 208}, {112, 250, -27}, },
            {{97, 97, 209}, },
            {{65, 108, -129}, {109, 109, 210}, {110, 250, -167}, },
            {{65, 250, -24}, },
            {{65, 250, -24}, },
            {{32, 32, 211}, },
            {{65, 100, -34}, {101, 101, 212}, {102, 250, -34}, },
            {{99, 99, 213}, },
            {{65, 109, -29}, {110, 110, 214}, {111, 250, -29}, },
            {{108, 108, 215}, },
            {{65, 115, -134}, {116, 116, 216}, {117, 250, -130}, },
            {{97, 97, 217}, },
            {{65, 110, -27}, {111, 111, 218}, {112, 250, -27}, },
            {{115, 115, 219}, },
            {{65, 250, -24}, },
            {{115, 115, 220}, },
            {{101, 101, 221}, },
            {},
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 42, 42, 42, 42, 35, 32, 23, 12, 13, 30, 29, 25, 28, 36, 31, 37, 37, -1, 24, 34, 27, 39, 40, 39, 39, 39, 21, 39, 39, 39, 39, 39, 39, 39, 39, -1, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, -1, 37, -1, 37, 37, -1, -1, 26, 33, 10, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 39, 39, 39, 39, 39, 39, 39, 39, 39, 22, 39, 39, 15, 39, 39, 39, -1, -1, 41, -1, 38, 37, 37, -1, -1, 38, 39, 39, 39, 39, 39, 39, 39, 39, 39, 7, 39, 39, 39, 39, 39, 39, 5, -1, 38, 8, 39, 39, 6, 39, 39, 39, 39, 39, 39, 39, 9, 39, 39, 19, 39, 39, 39, 17, 20, 39, 39, 39, 39, 16, 39, 0, 2, 39, -1, 14, 4, 39, 39, 39, -1, 39, 3, 18, -1, 39, -1, 39, -1, 39, -1, 39, -1, 11, -1, -1, 1, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
