/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.node;

import java.util.*;
import calculadora.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaraObjDec extends PDec
{
    private final LinkedList<PIdentifica> _identifica_ = new LinkedList<PIdentifica>();

    public ADeclaraObjDec()
    {
        // Constructor
    }

    public ADeclaraObjDec(
        @SuppressWarnings("hiding") List<?> _identifica_)
    {
        // Constructor
        setIdentifica(_identifica_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaraObjDec(
            cloneList(this._identifica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaraObjDec(this);
    }

    public LinkedList<PIdentifica> getIdentifica()
    {
        return this._identifica_;
    }

    public void setIdentifica(List<?> list)
    {
        for(PIdentifica e : this._identifica_)
        {
            e.parent(null);
        }
        this._identifica_.clear();

        for(Object obj_e : list)
        {
            PIdentifica e = (PIdentifica) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._identifica_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifica_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PIdentifica> i = this._identifica_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PIdentifica) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
