/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.node;

import java.util.*;
import calculadora.analysis.*;

@SuppressWarnings("nls")
public final class ADecFuncaoDeclara extends PDeclara
{
    private PTipo _esq_;
    private final LinkedList<PParametro> _mid_ = new LinkedList<PParametro>();
    private PExp _dir_;

    public ADecFuncaoDeclara()
    {
        // Constructor
    }

    public ADecFuncaoDeclara(
        @SuppressWarnings("hiding") PTipo _esq_,
        @SuppressWarnings("hiding") List<?> _mid_,
        @SuppressWarnings("hiding") PExp _dir_)
    {
        // Constructor
        setEsq(_esq_);

        setMid(_mid_);

        setDir(_dir_);

    }

    @Override
    public Object clone()
    {
        return new ADecFuncaoDeclara(
            cloneNode(this._esq_),
            cloneList(this._mid_),
            cloneNode(this._dir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecFuncaoDeclara(this);
    }

    public PTipo getEsq()
    {
        return this._esq_;
    }

    public void setEsq(PTipo node)
    {
        if(this._esq_ != null)
        {
            this._esq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esq_ = node;
    }

    public LinkedList<PParametro> getMid()
    {
        return this._mid_;
    }

    public void setMid(List<?> list)
    {
        for(PParametro e : this._mid_)
        {
            e.parent(null);
        }
        this._mid_.clear();

        for(Object obj_e : list)
        {
            PParametro e = (PParametro) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._mid_.add(e);
        }
    }

    public PExp getDir()
    {
        return this._dir_;
    }

    public void setDir(PExp node)
    {
        if(this._dir_ != null)
        {
            this._dir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._esq_)
            + toString(this._mid_)
            + toString(this._dir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._esq_ == child)
        {
            this._esq_ = null;
            return;
        }

        if(this._mid_.remove(child))
        {
            return;
        }

        if(this._dir_ == child)
        {
            this._dir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._esq_ == oldChild)
        {
            setEsq((PTipo) newChild);
            return;
        }

        for(ListIterator<PParametro> i = this._mid_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PParametro) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._dir_ == oldChild)
        {
            setDir((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
