/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.node;

import java.util.*;
import calculadora.analysis.*;

@SuppressWarnings("nls")
public final class ADefClasseDefClasse extends PDefClasse
{
    private final LinkedList<PDec> _esq_ = new LinkedList<PDec>();
    private final LinkedList<PDeclara> _dir_ = new LinkedList<PDeclara>();

    public ADefClasseDefClasse()
    {
        // Constructor
    }

    public ADefClasseDefClasse(
        @SuppressWarnings("hiding") List<?> _esq_,
        @SuppressWarnings("hiding") List<?> _dir_)
    {
        // Constructor
        setEsq(_esq_);

        setDir(_dir_);

    }

    @Override
    public Object clone()
    {
        return new ADefClasseDefClasse(
            cloneList(this._esq_),
            cloneList(this._dir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefClasseDefClasse(this);
    }

    public LinkedList<PDec> getEsq()
    {
        return this._esq_;
    }

    public void setEsq(List<?> list)
    {
        for(PDec e : this._esq_)
        {
            e.parent(null);
        }
        this._esq_.clear();

        for(Object obj_e : list)
        {
            PDec e = (PDec) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._esq_.add(e);
        }
    }

    public LinkedList<PDeclara> getDir()
    {
        return this._dir_;
    }

    public void setDir(List<?> list)
    {
        for(PDeclara e : this._dir_)
        {
            e.parent(null);
        }
        this._dir_.clear();

        for(Object obj_e : list)
        {
            PDeclara e = (PDeclara) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._dir_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._esq_)
            + toString(this._dir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._esq_.remove(child))
        {
            return;
        }

        if(this._dir_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PDec> i = this._esq_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDec) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PDeclara> i = this._dir_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDeclara) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
