/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.node;

import java.util.*;
import calculadora.analysis.*;

@SuppressWarnings("nls")
public final class AProgramaPrograma extends PPrograma
{
    private PFamilia _esq_;
    private final LinkedList<PDefClasse> _dir_ = new LinkedList<PDefClasse>();

    public AProgramaPrograma()
    {
        // Constructor
    }

    public AProgramaPrograma(
        @SuppressWarnings("hiding") PFamilia _esq_,
        @SuppressWarnings("hiding") List<?> _dir_)
    {
        // Constructor
        setEsq(_esq_);

        setDir(_dir_);

    }

    @Override
    public Object clone()
    {
        return new AProgramaPrograma(
            cloneNode(this._esq_),
            cloneList(this._dir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgramaPrograma(this);
    }

    public PFamilia getEsq()
    {
        return this._esq_;
    }

    public void setEsq(PFamilia node)
    {
        if(this._esq_ != null)
        {
            this._esq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esq_ = node;
    }

    public LinkedList<PDefClasse> getDir()
    {
        return this._dir_;
    }

    public void setDir(List<?> list)
    {
        for(PDefClasse e : this._dir_)
        {
            e.parent(null);
        }
        this._dir_.clear();

        for(Object obj_e : list)
        {
            PDefClasse e = (PDefClasse) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._dir_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._esq_)
            + toString(this._dir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._esq_ == child)
        {
            this._esq_ = null;
            return;
        }

        if(this._dir_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._esq_ == oldChild)
        {
            setEsq((PFamilia) newChild);
            return;
        }

        for(ListIterator<PDefClasse> i = this._dir_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDefClasse) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
