/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.node;

import java.util.*;
import calculadora.analysis.*;

@SuppressWarnings("nls")
public final class ARelacionamentosFamilia extends PFamilia
{
    private final LinkedList<PRelacionamento> _relacionamento_ = new LinkedList<PRelacionamento>();

    public ARelacionamentosFamilia()
    {
        // Constructor
    }

    public ARelacionamentosFamilia(
        @SuppressWarnings("hiding") List<?> _relacionamento_)
    {
        // Constructor
        setRelacionamento(_relacionamento_);

    }

    @Override
    public Object clone()
    {
        return new ARelacionamentosFamilia(
            cloneList(this._relacionamento_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelacionamentosFamilia(this);
    }

    public LinkedList<PRelacionamento> getRelacionamento()
    {
        return this._relacionamento_;
    }

    public void setRelacionamento(List<?> list)
    {
        for(PRelacionamento e : this._relacionamento_)
        {
            e.parent(null);
        }
        this._relacionamento_.clear();

        for(Object obj_e : list)
        {
            PRelacionamento e = (PRelacionamento) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._relacionamento_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._relacionamento_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._relacionamento_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PRelacionamento> i = this._relacionamento_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PRelacionamento) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
