/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.node;

import calculadora.analysis.*;

@SuppressWarnings("nls")
public final class ARelacionamentoRelacionamento extends PRelacionamento
{
    private PFilha _filha_;

    public ARelacionamentoRelacionamento()
    {
        // Constructor
    }

    public ARelacionamentoRelacionamento(
        @SuppressWarnings("hiding") PFilha _filha_)
    {
        // Constructor
        setFilha(_filha_);

    }

    @Override
    public Object clone()
    {
        return new ARelacionamentoRelacionamento(
            cloneNode(this._filha_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelacionamentoRelacionamento(this);
    }

    public PFilha getFilha()
    {
        return this._filha_;
    }

    public void setFilha(PFilha node)
    {
        if(this._filha_ != null)
        {
            this._filha_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._filha_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._filha_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._filha_ == child)
        {
            this._filha_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._filha_ == oldChild)
        {
            setFilha((PFilha) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
