/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.node;

import calculadora.analysis.*;

@SuppressWarnings("nls")
public final class ATipoClasseTipoClasse extends PTipoClasse
{
    private TClIdentificador _clIdentificador_;

    public ATipoClasseTipoClasse()
    {
        // Constructor
    }

    public ATipoClasseTipoClasse(
        @SuppressWarnings("hiding") TClIdentificador _clIdentificador_)
    {
        // Constructor
        setClIdentificador(_clIdentificador_);

    }

    @Override
    public Object clone()
    {
        return new ATipoClasseTipoClasse(
            cloneNode(this._clIdentificador_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATipoClasseTipoClasse(this);
    }

    public TClIdentificador getClIdentificador()
    {
        return this._clIdentificador_;
    }

    public void setClIdentificador(TClIdentificador node)
    {
        if(this._clIdentificador_ != null)
        {
            this._clIdentificador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._clIdentificador_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._clIdentificador_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._clIdentificador_ == child)
        {
            this._clIdentificador_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._clIdentificador_ == oldChild)
        {
            setClIdentificador((TClIdentificador) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
