/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.analysis;

import java.util.*;
import calculadora.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProgramaPrograma(AProgramaPrograma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARelacionamentosFamilia(ARelacionamentosFamilia node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARelacionamentoRelacionamento(ARelacionamentoRelacionamento node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFilhaFilha(AFilhaFilha node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADefClasseDefClasse(ADefClasseDefClasse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdentificadorIdentifica(AIdentificadorIdentifica node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInitInicializar(AInitInicializar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADeclaraObjDec(ADeclaraObjDec node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADeclaraVariavelDec(ADeclaraVariavelDec node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADeclaraConstanteDec(ADeclaraConstanteDec node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecProcedimentoDeclara(ADecProcedimentoDeclara node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecFuncaoDeclara(ADecFuncaoDeclara node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParametroParametro(AParametroParametro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATipoClasseTipo(ATipoClasseTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATipoPrimtivoTipo(ATipoPrimtivoTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATipoClasseTipoClasse(ATipoClasseTipoClasse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIntTipoPrimitivo(AIntTipoPrimitivo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABoolTipoPrimitivo(ABoolTipoPrimitivo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARealTipoPrimitivo(ARealTipoPrimitivo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInteiroNumero(AInteiroNumero node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARealNumero(ARealNumero node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVerdadeiroBooleano(AVerdadeiroBooleano node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFalsoBooleano(AFalsoBooleano node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAtributoAtributo(AAtributoAtributo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASeComando(ASeComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComandoComando(AComandoComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComandoEnquantoComando(AComandoEnquantoComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComandoAtribComando(AComandoAtribComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAtributoComando(AAtributoComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoComando(ABlocoComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAObjectObject(AObjectObject node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASeExp(ASeExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEntaoExp(AEntaoExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASenaoExp(ASenaoExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEnquantoExpExp(AEnquantoExpExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMaisExp(AMaisExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMenosExp(AMenosExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultExp(AMultExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADivExp(ADivExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAModExp(AModExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACompExp(ACompExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMenorExp(AMenorExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoDelimitExp(ABlocoDelimitExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANumNegativoExp(ANumNegativoExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAndExp(AAndExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOrExp(AOrExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdAtribExp(AIdAtribExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdAtributoExp(AIdAtributoExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANumExp(ANumExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANumBoolExp(ANumBoolExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTClasse(TClasse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFilhaDaClasse(TFilhaDaClasse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComeca(TComeca node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTermina(TTermina node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTObjeto(TObjeto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVariavel(TVariavel node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTConstante(TConstante node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInteiro(TInteiro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBool(TBool node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTReal(TReal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIniciaProcdm(TIniciaProcdm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTProcedimento(TProcedimento node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParEsquerdo(TParEsquerdo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParDireito(TParDireito node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFuncao(TFuncao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSe(TSe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSenao(TSenao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEntao(TEntao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEnquanto(TEnquanto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVerdadeiro(TVerdadeiro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFalso(TFalso node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTE(TE node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOu(TOu node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEComercial(TEComercial node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPontoVirgula(TPontoVirgula node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVirgula(TVirgula node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInicializacao(TInicializacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAtribuicao(TAtribuicao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMenos(TMenos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMais(TMais node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMult(TMult node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDiv(TDiv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMod(TMod node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComp(TComp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMenor(TMenor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNegacao(TNegacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPonto(TPonto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumInteiro(TNumInteiro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumReal(TNumReal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIdentificador(TIdentificador node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTClIdentificador(TClIdentificador node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComent(TComent node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVazio(TVazio node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
